In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("Bengaluru_House_Data.csv")
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [3]:
df.shape

(13320, 9)

In [4]:
df=df[df['size'].notnull()]

In [5]:
# This cell previously caused the 'size' column to become NaN. Its content has been removed to allow 'bhk' extraction to work correctly.

In [6]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [7]:
df['bhk'] = df['size'].astype(str).str.split().str[0]
df['bhk'] = pd.to_numeric(df['bhk'], errors='coerce')

/tmp/ipykernel_2434/1482741617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bhk'] = df['size'].astype(str).str.split().str[0]
/tmp/ipykernel_2434/1482741617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bhk'] = pd.to_numeric(df['bhk'], errors='coerce')

In [8]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1

In [9]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1

In [10]:
def convert_sqft_to_num(x):
    if isinstance(x, (int, float)): # Already numeric
        return x
    try:
        tokens = x.split('-')
        if len(tokens) == 2:
            # It's a range, take the average
            return (float(tokens[0]) + float(tokens[1])) / 2
    except:
        pass
    try:
        # Try to convert directly to float, handling various units
        # Remove non-numeric characters except '.' and handle common unit suffixes
        if 'Sq. Meter' in x:
            return float(x.replace('Sq. Meter', '').strip()) * 10.764 # Convert to sqft
        elif 'Perch' in x:
            return float(x.replace('Perch', '').strip()) * 272.25 # Convert to sqft
        elif 'Sq. Yards' in x:
            return float(x.replace('Sq. Yards', '').strip()) * 9 # Convert to sqft
        elif 'Cents' in x:
            return float(x.replace('Cents', '').strip()) * 435.6 # Convert to sqft
        elif 'Guntha' in x:
            return float(x.replace('Guntha', '').strip()) * 1089 # Convert to sqft
        elif 'Acres' in x:
            return float(x.replace('Acres', '').strip()) * 43560 # Convert to sqft
        else:
            # Try to convert directly to float, removing any non-numeric characters
            # This catches cases like '1056' or '2500.00'
            return float(''.join(filter(lambda c: c.isdigit() or c == '.', x)))
    except:
        pass
    return np.nan # Return NaN for invalid values

df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

df.head()

/tmp/ipykernel_2434/2633176229.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2

In [11]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

/tmp/ipykernel_2434/4168263592.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

### Handling Outliers in `price_per_sqft`

It's common to find outliers in real estate data, especially in price-related metrics. We will remove outliers using the standard deviation for `price_per_sqft` per location. A common approach is to keep data points that are within a certain standard deviation from the mean.

In [13]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']
df.head()

/tmp/ipykernel_2434/109161147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4,4615.384615
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3,4305.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3,6245.890861
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2,4250.000000

In [19]:
print(f"Original DataFrame shape: {df.shape}")

# Function to remove outliers based on price_per_sqft per location
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    k=df
    for key, subdf in df.groupby('location'):

        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
        k=subdf
    print(k)
    return df_out

df_cleaned = remove_pps_outliers(df)
print(f"DataFrame shape after removing price_per_sqft outliers: {df_cleaned.shape}")

df = df_cleaned # Update the main DataFrame
df.head()

Original DataFrame shape: (5206, 11)
                 area_type   availability location       size  society  \
3624  Super built-up  Area  Ready To Move    other      3 BHK  Sorisa
3625        Built-up  Area  Ready To Move    other      3 BHK  Sorisa
3626  Super built-up  Area  Ready To Move    other      3 BHK  Sorisa
3627        Built-up  Area  Ready To Move    other       1 RK  GMown E
3628  Super built-up  Area  Ready To Move    other      3 BHK      NaN
...                    ...            ...      ...        ...      ...
5201  Super built-up  Area  Ready To Move    other      6 BHK  Essic C
5202  Super built-up  Area         18-Nov    other      3 BHK      NaN
5203            Plot  Area  Ready To Move    other  2 Bedroom      NaN
5204            Plot  Area         18-Apr    other  2 Bedroom      NaN
5205            Plot  Area         18-Apr    other  3 Bedroom      NaN

      total_sqft  bath  balcony   price  bhk  price_per_sqft
3624      1672.0   3.0      2.0  150.00    3     8971.291866
3625      1750.0   3.0      3.0  149.00    3     8514.285714
3626      1750.0   3.0      2.0  150.00    3     8571.428571
3627       550.0   1.0      1.0   27.00    1     4909.090909
3628      1450.0   2.0      2.0   70.00    3     4827.586207
...          ...   ...      ...     ...  ...             ...
5201      3800.0   6.0      NaN  390.00    6    10263.157895
5202      1780.0   3.0      1.0   84.83    3     4765.730337
5203       880.0   2.0      1.0   48.00    2     5454.545455
5204      1000.0   2.0      1.0   55.00    2     5500.000000
5205      1400.0   2.0      1.0   78.00    3     5571.428571

[1582 rows x 11 columns]
DataFrame shape after removing price_per_sqft outliers: (3434, 11)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,Ready To Move,Devarachikkanahalli,3 BHK,Wiaysld,1705.0,3.0,2.0,75.0,3,4398.826979
1,Built-up Area,Ready To Move,Devarachikkanahalli,2 BHK,Sarch M,1116.0,2.0,1.0,47.0,2,4211.469534
2,Super built-up Area,Ready To Move,Devarachikkanahalli,3 BHK,Heate L,1700.0,3.0,1.0,71.0,3,4176.470588
3,Super built-up Area,Ready To Move,1st Phase JP Nagar,3 BHK,NCaveun,2024.0,3.0,NaN,157.0,3,7756.916996
4,Super built-up Area,18-May,1st Phase JP Nagar,2 BHK,Inntsth,1077.0,2.0,2.0,93.0,2,8635.097493

### Exploring Categorical Features: `location`

The `location` column is a categorical feature, and it's essential to understand its unique values and their frequencies. High cardinality in this column might require dimensionality reduction techniques before one-hot encoding.

In [15]:
location_stats = df['location'].value_counts(ascending=False)
display(location_stats)

# How many locations have less than 10 data points?
location_less_than_10 = location_stats[location_stats <= 10]
print(f"\nNumber of locations with less than 10 data points: {len(location_less_than_10)}")

location
Whitefield                        536
Sarjapur  Road                    396
Electronic City                   285
Kanakpura Road                    203
Yelahanka                         185
                                 ...
 south                              1
Yeshwanthpur Industrial Suburb      1
frazertown                          1
manyata park                        1
 Electronic City                    1
Name: count, Length: 810, dtype: int64

Number of locations with less than 10 data points: 621

Given the large number of locations with few data points, we'll categorize them as 'other' to reduce dimensionality and avoid issues with one-hot encoding sparse categories.

In [16]:
df['location'] = df['location'].apply(lambda x: 'other' if x in location_less_than_10 else x)
print(f"Number of unique locations after grouping 'other': {len(df['location'].unique())}")
df.head()

Number of unique locations after grouping 'other': 190

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,Ready To Move,other,3 BHK,Sorisa,1672.0,3.0,2.0,150.0,3,8971.291866
1,Built-up Area,Ready To Move,other,3 BHK,Sorisa,1750.0,3.0,3.0,149.0,3,8514.285714
2,Super built-up Area,Ready To Move,other,3 BHK,Sorisa,1750.0,3.0,2.0,150.0,3,8571.428571
3,Super built-up Area,18-May,Devarachikkanahalli,3 BHK,NaN,1250.0,2.0,3.0,44.0,3,3520.000000
4,Super built-up Area,Ready To Move,Devarachikkanahalli,2 BHK,Clntsrt,1250.0,2.0,2.0,40.0,2,3200.000000

In [20]:
# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np

# ================================
# 2. LOAD DATA
# ================================
df = pd.read_csv('Bengaluru_House_Data.csv')

# ================================
# 3. DROP UNNECESSARY COLUMNS
# ================================
# These columns are not useful for prediction
df = df.drop(['availability', 'society', 'balcony'], axis=1)

# ================================
# 4. HANDLE MISSING VALUES
# ================================
# Drop rows where important values are missing
df = df.dropna(subset=['location', 'size', 'total_sqft', 'bath'])

# ================================
# 5. CLEAN 'SIZE' COLUMN → CREATE BHK
# ================================
# Extract number from "2 BHK", "4 Bedroom"
df['bhk'] = df['size'].astype(str).str.split().str[0]

# Convert to numeric safely
df['bhk'] = pd.to_numeric(df['bhk'], errors='coerce')

# ================================
# 6. CLEAN 'TOTAL_SQFT'
# ================================
# Convert ranges like "1200-1500" → average

def convert_sqft(x):
    try:
        if '-' in str(x):
            a, b = x.split('-')
            return (float(a) + float(b)) / 2
        return float(x)
    except:
        return np.nan

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

# ================================
# 7. FEATURE ENGINEERING
# ================================
# Create price per sqft (price is in lakhs → multiply)
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

# ================================
# 8. REMOVE OUTLIERS (BHK LOGIC)
# ================================
# Minimum 300 sqft per BHK
df = df[df['total_sqft'] / df['bhk'] >= 300]

# ================================
# 9. REMOVE OUTLIERS (PRICE PER SQFT)
# ================================
def remove_pps_outliers(df):
    df_out = pd.DataFrame()

    for location, subdf in df.groupby('location'):
        m = subdf['price_per_sqft'].mean()
        st = subdf['price_per_sqft'].std()

        # Keep only values within (mean ± std)
        reduced_df = subdf[
            (subdf['price_per_sqft'] > (m - st)) &
            (subdf['price_per_sqft'] <= (m + st))
        ]

        df_out = pd.concat([df_out, reduced_df], ignore_index=True)

    return df_out

df = remove_pps_outliers(df)

# ================================
# 10. CLEAN LOCATION COLUMN
# ================================
# Remove extra spaces
df['location'] = df['location'].apply(lambda x: x.strip())

# Count number of data points per location
location_stats = df.groupby('location')['location'].count()

# Find rare locations (<=10 data points)
location_stats_less_than_10 = location_stats[location_stats <= 10]

# Replace rare locations with "other"
df['location'] = df['location'].apply(
    lambda x: 'other' if x in location_stats_less_than_10 else x
)

# ================================
# 11. ONE HOT ENCODING
# ================================
# Convert categorical columns into numeric
df = pd.get_dummies(df, columns=['location', 'area_type'], drop_first=True)

# ================================
# 12. DROP UNUSED COLUMNS
# ================================
# 'size' not needed anymore
df = df.drop(['size'], axis=1)

# ================================
# FINAL DATA
# ================================
df.head()

,total_sqft,bath,price,bhk,price_per_sqft,location_5th Phase JP Nagar,location_6th Phase JP Nagar,location_7th Phase JP Nagar,location_8th Phase JP Nagar,location_9th Phase JP Nagar,...,location_Vittasandra,location_Whitefield,location_Yelachenahalli,location_Yelahanka,location_Yelahanka New Town,location_Yeshwanthpur,location_other,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,1100.0,2.0,70.0,2,6363.636364,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
1,1672.0,3.0,150.0,3,8971.291866,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
2,1750.0,3.0,149.0,3,8514.285714,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,1750.0,3.0,150.0,3,8571.428571,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
4,1250.0,2.0,44.0,3,3520.000000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [22]:
# ================================
# 1. IMPORT LIBRARIES
# ================================
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# ================================
# 2. DEFINE FEATURES & TARGET
# ================================
X = df.drop(['price'], axis=1)
y = df['price']

# ================================
# 3. TRAIN TEST SPLIT
# ================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ================================
# 4. TRAIN MODELS
# ================================

# Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# Decision Tree
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

# Random Forest
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# ================================
# 5. EVALUATION FUNCTION
# ================================
def evaluate_model(y_test, y_pred, model_name):
    print(f"\n🔹 {model_name} Performance")
    print("R2 Score:", r2_score(y_test, y_pred))
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# ================================
# 6. EVALUATE ALL MODELS
# ================================
evaluate_model(y_test, y_pred_lr, "Linear Regression")
evaluate_model(y_test, y_pred_dt, "Decision Tree")
evaluate_model(y_test, y_pred_rf, "Random Forest")

🔹 Linear Regression Performance
R2 Score: 0.8346585613922256
MAE: 16.20132089264373
RMSE: 51.51420413033187

🔹 Decision Tree Performance
R2 Score: 0.9083506384286971
MAE: 3.6108723958333333
RMSE: 38.3531342433583

🔹 Random Forest Performance
R2 Score: 0.9627619215786687
MAE: 1.9342308854166665
RMSE: 24.44723626319372

In [24]:
import pickle
pickle.dump(rf, open('model.pkl', 'wb'))

In [26]:
import pickle

pickle.dump(X.columns, open('columns.pkl', 'wb'))

In [27]:
sqft = 1200
bhk = 2
bath = 2
location = "Whitefield"

In [30]:
import pickle
import pandas as pd

# Load model + columns
model = pickle.load(open('model.pkl', 'rb'))
columns = pickle.load(open('columns.pkl', 'rb'))

# Input
sqft = 400
bhk = 3
bath = 2
location = "Whitefield"

# Create input dataframe
input_df = pd.DataFrame(columns=columns)
input_df.loc[0] = 0

input_df['total_sqft'] = sqft
input_df['bath'] = bath
input_df['bhk'] = bhk

# Set location
loc_col = "location_" + location
if loc_col in input_df.columns:
    input_df[loc_col] = 1

# Predict
prediction = model.predict(input_df)[0]

print("Prediction:", prediction)

Prediction: 10.523